version: "3.1"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "6060:6060"
    environment:
      - KEYCLOAK_USER=gridcapa
      - KEYCLOAK_PASSWORD=gridcapa
    volumes:
      - keycloak-data:/data

volumes:
  keycloak-data: